# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170825_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='group',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
