# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20170825_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inbox',
            old_name='email',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='inbox',
            old_name='name',
            new_name='recipent',
        ),
        migrations.AlterField(
            model_name='contact',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='app.Group'),
        ),
    ]
