# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20170828_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipent', models.CharField(max_length=300)),
                ('message', models.CharField(max_length=300)),
                ('subject', models.CharField(max_length=300)),
                ('date', models.DateField()),
            ],
        ),
    ]
